apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: guh7np1uf-nodejs 
  janus-idp.io/tekton: guh7np1uf-nodejs
  backstage.io/kubernetes-id: guh7np1uf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: guh7np1uf-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  