apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: guh7np1uf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: guh7np1uf-nodejs 
  name: guh7np1uf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: guh7np1uf-nodejs 
